### ISSUE TITLE
Consider "unknown" or "unparsed" type

### ISSUE THREAD

**Issue by vsoch** [buildsi/Smeagle#66]
We currently leave out a parsing if we've seen it before. This approach would instead add an "unknown" type (or similar named, something along the lines of being left out) instead.

**Comment by vsoch** [comment]
And we already seem to be using unknown for import export...
```
        {
          "name":"structZthyjfbdvfbcet",
          "type":"STRUCTstructZthyjfbdvfbcet *",
          "class":"Pointer",
          "location":"%rdi",
          "direction":"unknown",
          "size":"8",
          "indirections":"1",
          "underlying_type":             {
              "type":"STRUCTstructZthyjfbdvfbcet",
              "class":"Struct",
              "size":"4",
              "fields": [
               {
                 "name":"fpIntGzryoclchfdmp",
                 "type":"short int",
                 "class":"Scalar",
                 "size":"2"
               },               {
                 "name":"fpIntDcvmaaefaczzoel",
                 "type":"short int",
                 "class":"Scalar",
                 "size":"2"
               }]
            }}
    ]
```

**Comment by hainest** [comment]
We can close this issue. Smeagle correctly represents already-seen types to prevent unbound recursion in type parsing. Already-seen types are expanded inline with the current context using the `underlying_type` key. If a type `Foo` is encountered N times, it will be represented N times. This could be optimized, but would require significant rewriting of Smeagle's type parser. In essence, we would be recreating the DWARF contained in the binary from Symtab's expanded, parsed DWARF. I don't think we should go down that path.

Example:

Example:

    struct Foo;
    struct Bar {
      Bar *b;
      Foo *f;
      int x;
    };
    struct Foo {
      Bar b;
      Foo *f;
      int y;
    };

    void bar(Bar b){}
    void foo(Foo f){}

Smeagle produces:

    {
      "library": "libtest.so",
      "locations": [
        {
          "function": {
            "name": "_Z3foo3Foo",
            "parameters": [
              {
                "name": "f",
                "type": "Foo",
                "class": "Struct",
                "location": "%rdi",
                "direction": "import",
                "size": "40",
                "fields": [
                  {
                    "name": "b",
                    "type": "Bar",
                    "class": "Struct",
                    "size": "24",
                    "fields": [
                      {
                        "name": "b",
                        "type": "Bar",
                        "class": "Pointer",
                        "size": "8",
                        "indirections": "1",
                        "underlying_type": {
                          "name": "b",
                          "type": "Bar *",
                          "class": "Struct",
                          "size": "8"
                        }
                      },
                      {
                        "name": "f",
                        "type": "Foo",
                        "class": "Pointer",
                        "size": "8",
                        "indirections": "1",
                        "underlying_type": {
                          "name": "f",
                          "type": "Foo *",
                          "class": "Struct",
                          "size": "8"
                        }
                      },
                      {
                        "name": "x",
                        "type": "int",
                        "class": "Scalar",
                        "size": "4"
                      }
                    ]
                  },
                  {
                    "name": "f",
                    "type": "Foo",
                    "class": "Pointer",
                    "size": "8",
                    "indirections": "1",
                    "underlying_type": {
                      "name": "f",
                      "type": "Foo *",
                      "class": "Struct",
                      "size": "8"
                    }
                  },
                  {
                    "name": "y",
                    "type": "int",
                    "class": "Scalar",
                    "size": "4"
                  }
                ]
              }
            ]
          }
        },
        {
          "function": {
            "name": "_Z3bar3Bar",
            "parameters": [
              {
                "name": "b",
                "type": "Bar",
                "class": "Struct",
                "location": "%rdi",
                "direction": "import",
                "size": "24",
                "fields": [
                  {
                    "name": "b",
                    "type": "Bar",
                    "class": "Pointer",
                    "size": "8",
                    "indirections": "1",
                    "underlying_type": {
                      "name": "b",
                      "type": "Bar *",
                      "class": "Struct",
                      "size": "8"
                    }
                  },
                  {
                    "name": "f",
                    "type": "Foo",
                    "class": "Pointer",
                    "size": "8",
                    "indirections": "1",
                    "underlying_type": {
                      "name": "f",
                      "type": "Foo *",
                      "class": "Struct",
                      "size": "8",
                      "fields": [
                        {
                          "name": "b",
                          "type": "Bar",
                          "class": "Struct",
                          "size": "24"
                        },
                        {
                          "name": "f",
                          "type": "Foo",
                          "class": "Pointer",
                          "size": "8",
                          "indirections": "1",
                          "underlying_type": {
                            "name": "f",
                            "type": "Foo *",
                            "class": "Struct",
                            "size": "8"
                          }
                        },
                        {
                          "name": "y",
                          "type": "int",
                          "class": "Scalar",
                          "size": "4"
                        }
                      ]
                    }
                  },
                  {
                    "name": "x",
                    "type": "int",
                    "class": "Scalar",
                    "size": "4"
                  }
                ]
              }
            ]
          }
        }
      ]
    }

**Comment by vsoch** [comment]
I agree with Tim - if we represent an already seen type somewhere in the tree our model is going to catch it. We don't need to redundantly reference is (and make the data output bigger and the generation more complex than it needs to be).
