### ISSUE TITLE
Is `Smeagle` an alternate spelling of `Smeagol`?

### ISSUE THREAD

**Issue by becker33** [buildsi/Smeagle#7]
Assuming we're going with an `elf`/`dwarf`/`hobbit`/`gollum`/`smeagol` theme

**Comment by vsoch** [comment]
It's just an alternative spelling, I liked how it looked better than Smeagol. :)

**Comment by vsoch** [comment]
If we find something good for S and M, it could be "something something Eagle." That's probably why I liked the spelling - it has "eagle" in it, implying a strong, watchful eye.
